name: datajudge
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - pytest
  - pytest-cov
  - pytest-html
  - make
  - numpydoc
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - pre-commit
  - pyodbc
  - sqlalchemy
  - psycopg2
  - freetds
  - snowflake-sqlalchemy>=1.4.0
  - sqlalchemy-bigquery
  - flit-core
  - flit
  - pytest-cov
  - sphinx-autodoc-typehints
